### ISSUE TITLE
Enhancement: add_object()

### ISSUE THREAD

**Issue by MScottBlake** [sheagcraig/python-jss#26]
Can we get a wrapper method to add an object to an already selected object?

```python
import jss
j = jss.JSS(jss.JSSPrefs())

foo_site = j.Site("Foo")
new_policy = jss.Policy(j, "New Policy TEST")
new_policy.add_object_to_path(foo_site, "general")
```
The idea is to make the above code rewritable as the following code.
```python
import jss
j = jss.JSS(jss.JSSPrefs())

foo_site = j.Site("Foo")
new_policy = jss.Policy(j, "New Policy TEST")
new_policy.find("general").add_object(foo_site)
```

Often times there is a need to make multiple changes to a tag (in this case "general"), so a variable may be used `new_policy_general = new_policy.find("general")` to decrease the number of lookups.

**Comment by sheagcraig** [comment]
There should be an existing way to do this using etree and ```JSSContainerObject.as_list_data()```.

i.e.
```
import jss
j = jss.JSS(jss.JSSPrefs())

foo_site = j.Site("Foo")
new_policy = jss.Policy(j, "New Policy TEST")
new_policy.find("general").append(new_policy.as_list_data())
```

This may not encompass *all* objects that could be added, since the ```as_list_data``` method is currently only defined for ```JSSContainerObject``` and its children, since it didn't make sense elsewhere. Certainly, it would work in the example you've given.

**Comment by sheagcraig** [comment]
@MScottBlake I just took a look at this as part of my cleanup prior to 0.5.6.

One problem with implementing a add_object method has to do with the method chaining and return values involved.

It seems logical to have a ```JSSObject.add_object``` method (that is where ```JSSObject.add_object_at_path``` is defined).

However, in your example, you do:
``` new_policy.find("general").add_object(foo_site)```
Unravelled, this first call to ```new_policy.find()``` returns an ```xml.etree.Element```, not a ```JSSObject```, and thus, has no method named ```add_object```.

I can't override ```find``` to just return a ```JSSObject```, because it doesn't make sense for what is essentially a single element to have all of the ```JSSObject``` methods and properties.

I  *could* subclass ```Element``` AND override ```JSSObject.find```, but I don't feel like that's the right thing to do when you can instead fairly easily use the solution provided above, i.e.:
```
new_policy.find("general").append(new_policy.as_list_data())
```

But I'm no expert on OOP, so if you can think of an elegant way to do this, let me know!
