### ISSUE TITLE
"easy_install python-jss" installs 1.2.0, not current release

### ISSUE THREAD

**Issue by rougegoat** [sheagcraig/python-jss#43]
I was having a lot of trouble getting JSS_helper to work, but I think I've narrowed down the cause.  The instructions on that project tell you to run "sudo easy_install python-jss" to get the required version of python-jss.  Running that recommended command installs v1.2.0 of python-jss.  The current version of jss_helper then refuses to run citing a need for version 1.3 of python-jss to be installed.  Here's the output from that command:

```
Searching for python-jss
Best match: python-jss 1.2.0
Processing python_jss-1.2.0-py2.7.egg
python-jss 1.2.0 is already the active version in easy-install.pth

Using /Library/Python/2.7/site-packages/python_jss-1.2.0-py2.7.egg
Processing dependencies for python-jss
Finished processing dependencies for python-jss
titan:~ <username>$ jss_helper
Requires python-jss version: 1.3. Installed: 1.2
```

I'm guessing something didn't get updated quite right when the new version of python-jss was released.  So it's downloading an older release rather than the current official one.  That said, I haven't been able to locate the code that handles the easy_install, so I can't verify things on that.

**Comment by rougegoat** [comment]
Interestingly enough, doing the same thing on another machine leads to it failing entirely citing an invalid version number of "1.2.0rc1".

**Comment by sheagcraig** [comment]
So, there's something I don't seem to get when it comes to using
easy_install AND pip on the same machine. Is there any chance that you pip
installed it once? Or have you always used easy_install?

When I do an easy_install search for it on my machine, it returns 1.3.0 as
the newest version. Something is broken!

I'll check on some totally clean machines this week. I'll also try pip
installing, then easy_installing, to see why/how it breaks.

**Comment by rougegoat** [comment]
I always test new tools on a clean machine before trying them out on my main one.  I installed pip after running into the above issue.  I installed the pkg for jss_helper and then ran the easy_install and ran into the above issue.

**Comment by sheagcraig** [comment]
So I jumped on a brand new machine here and did
`sudo easy_install -U python-jss` and got 1.3.0 (1.4.0 is about to be the new "newest").

I then tried getting pip and updating python-jss.
`sudo easy_install -U pip` followed by
`sudo pip install -U python-jss`
which crashed and burned because it tried to remove a couple of dependencies (six and pyasn1) and then couldn't add them back.
So I ran
`sudo pip install -U python-jss` _again_ and it worked.
Then for fun I ran `sudo easy_install -U python-jss` a final time and it "worked", in the sense that it said the newest version was already installed.

What does this mean, however, if you have an older version that actually does need to get replaced?

I'm not really familiar with _how_ the two package managers work. It seems to me that it works correctly on a clean machine; but I'm going to test once I drop the new version here in a few hours, and see how this test machine does upgrading, especially after meddling with both pip and easy_install. I'll probably set another one up with just easy_install, and another with just pip so I can compare. Oh, and one that first installs with pip and then tries to upgrade with easy_install. Confusing!

Now, I think you can start over by just removing python-jss from the `/Library/Python/2.7/site-packages` folder. This includes anything that starts with python-jss OR jss.

easy_install adds the egg file to the site packages directory, and updates a file called easy-install.pth which you'll want to either remove or take out the lines referring to python-jss.

pip adds a python-jss .info file which includes packaging info, and puts the `jss` folder in site-packages. You'll need to remove both of those if they are present.

**Comment by sheagcraig** [comment]
Oops-didn't mean to send that right away.

Anyway, I would try sanitizing the site packages directory like mentioned above, and then try reinstalling.

The JSSImporter package uses easy_install to handle its dependencies, so that may force you to use easy_install for upgrades if you start from JSSImporter.

I'd like to switch to pip exclusively, but it doesn't come by default before 10.10.5 / python 2.7.10, so it would require an extra step; and for JSSImporter, I'm not super comfortable with installing pip on people's computers _for_ them.

**Comment by rougegoat** [comment]
I just ran through the same thing I did on Friday on a newly imaged machine.  It installed the correct version.  I guess it was a one day bug or something with my network or any number of things.  The important thing is that it's getting the right stuff.

**Comment by sheagcraig** [comment]
Thanks for the update-I'm glad that it finally worked!

In the meantime, I'm still going to go ahead with my mad-science
experiment. Hopefully I can get a 100% certainty on what happens between
the two package managers.
