### ISSUE TITLE
SSL Verification Behaviour

### ISSUE THREAD

**Issue by microservo** [sheagcraig/python-jss#49]
According to what I've undertand , seems that default behaviour is that SSL verification is always enabled, isnt't it ?

In the **jss_prefs.py** file there is a line 

_self.verify = prefs.get("verify", True)_

so if not specified, the SSL will be enabled, isn't it ?

I've fixed my issue ( at https://github.com/sheagcraig/jss_helper/issues/8) changing the value from True to False.
On my JSS test server I have an expired ssl certificates (problem that I will solve..) that without setting the SSL to False in the above file, doesn't allow me to use the toools (details of my error in the above link..)

I'm not a Python expert , so sorry if I've made some mistake :)

**Comment by sheagcraig** [comment]
I'm not sure that you've made a mistake. But yes, python-jss assumes that if you don't specify, that it should verify SSL certificates, as it's safer to assume more security rather than less.

I closed the aforementioned issue because the initial issue (unresponsive original poster) was unrelated.

I can see how an expired certificate would never verify! I'm not sure whether you're saying that you changed the code in jss_prefs.py or that you set your preferences to say you didn't want to verify SSL. The latter would be the "correct" approach.
