### ISSUE TITLE
Support for Python3

### ISSUE THREAD

**Issue by tmongero** [sheagcraig/python-jss#52]
This may come off as a bit of a noob question, but I'm still relatively new to Python..

I've been implementing AutoPkg (with the utilization of JSSImporter) for our JAMF instance at work, and I wanted to use the python-jss module specifically to take advantage of the JAMF API wrapper.. But I can't seem to get it to work with Python3.

In following the documentation, I'm able to `import jss`, but when I attempt to execute `jss_prefs = jss.JSSPrefs()`, and error is returned: `module 'jss' has no attribute 'JSSPrefs'`.

I've been wracking my brain over this and am wondering if this just doesn't work in python3. Any ideas?

**Comment by sheagcraig** [comment]
Honestly, I'm surprised it imported without complaint. I don't know that I've ever actually tried. I've toyed with the idea of using the six package to make it work on both 2 and 3, as I try to use 3 whenever possible.

I will say that the JSSPrefs class tries to do some PyObjC stuff to get at the preferences, and in most cases you don't just get PyObjC with Python3 unless you go out and get it (you _do_ get it with the system python on a Mac).

It takes _forever_, but if you have pip available, you can do `pip3 install pyobjc` and then try the above again to confirm.

That being said, python-jss was definitely developed with the Mac system python as the primary target, although I did run it on Linux for awhile also.

Just right off the bat, `grep -R print python-jss` gives me about 30 prints that will definitely not work in py3 because there aren't parentheses! That's probably the main issue, although I'm guessing unicode usage would need to be cleaned up thoroughly as well.

**Comment by tmongero** [comment]
I'd give the PyObjC install via pip3 a shot, but as you said with the differences in syntax between 2.7 and 3.5, I don't think it's worth it at this point. Do you have any plans to re-vamp this module for python3? I'd love to be able to use the module(s) within my own applets, but I'm not experienced enough just yet to be able to fork the module and carry out the conversion from 2.7 to 3.5.

**Comment by sheagcraig** [comment]
My goal is to indeed make this py3 compatible, but the timeline for that is not likely to happen any time soon. Honestly, you could try running the python 3 helper tool `2to3` against python-jss to get an idea of what needs to be fixed. It's predominantly print statements and using unicode instead of str.

My point is not that you should do the updating, but rather that for you to just use it in python2, even if you're learning 3, wouldn't be that big of a difference. Part of the reason it has always been targeted at 2 was because python 2 comes with Mac OS X, along with PyObjC without having to install or configure anything else. I would prefer to be doing everything with python 3 also, but this way I know that even apps I write for client machines will work without any extra work.

Of course, python-jss depends on requests also, so it's not like that argument is 100% accurate ;)

**Comment by tmongero** [comment]
Thanks for the info! I get it that python2 is still the standard because it's guaranteed to be on every machine.

Once I get to a point where I'm able to contribute to this, I'd love to help out. Cheers!
